silx-kit/hdf5plugin

setup.py

MacOS is also supported.

---

CHANGELOG.rst
README.rst
hdf5plugin/test.py
setup.py
test/test.py

This PR:
- Updates the changelog
- Renames built filters to strip Python related suffix, closes #20
- Embed the tests not relying on external data in the package, closes #21
- Add a `Testing` section in the readme

Updates following PR #18

---

appveyor.yml
setup.cfg
setup.py
test/test.py

This PR:
- Adds test with miniconda3
- Remove use of virtualenv (not really needed)

Add miniconda37 to test env on windows

---

README.rst
hdf5plugin/__init__.py
hdf5plugin/test.py
test/test.py

This PR adds some helpers and documentation to deal with compression options.

Add helper and documentation for compression options

---

setup.py
test/test.py

add bitshuffle compile args for windows and select them at build time

---

appveyor.yml

This PR tries to building with visual studio and testing with conda

Update windows CI

---

hdf5plugin/__init__.py
setup.py

This PR:
- Fixes a typo in the blosc compression name to id.
- Adds a `_` prefix to everything that is not public in the `__init__.py` file.

Fix typo and clean-up

---

hdf5plugin/__init__.py
hdf5plugin/test.py

added compression_opts function and changed blosc_options to private

---

README.rst

updated documentation

---

CHANGELOG.rst
README.rst
hdf5plugin/__init__.py
hdf5plugin/test.py

This PR updates the changelog (closes #39) and readme (feedbacks from #44).
It also fixes a few code style/indent typos.

Update changelog/readme and code style typos

---

CHANGELOG.rst
version.py

bump to version 2.1.0

---

setup.py

change -march -> mcpu option, flags may be non existing as well
close #61

compatibility with PPC64le

---

setup.py

it changed the meaning of the option !

replace -openmp with -fopenmp

---

CHANGELOG.rst
version.py

update changelog and bump version to 2.1.2

Prepare 2.1.2 release

---

CHANGELOG.rst
version.py

This PR prepares a v2.2 release: update changelog + bump version

Prepare 2.2 release

---

CHANGELOG.rst
version.py

- Update changelog
- Bump version to 2.3.0

Prepare 2.3 release

---

.github/workflows/ci.yml
src/c-blosc/internal-complibs/zlib-1.2.8/gzguts.h

Apply same patch as blosc to solve https://github.com/Blosc/python-blosc/issues/229

Patch zlib to allow compilation under MacOS and Python 3.8

---

CHANGELOG.rst
version.py

Update changelog and `version.py`
Advertise for drop of python2.7 in next release.

Prepare 2.3.2

---

.github/workflows/ci.yml

Following change of name of default branch in github.

CI: Updated to reflect change of default branch name

---

CHANGELOG.rst
src/hdf5plugin/_version.py

Update changelog, bump version

Prepare 3.0.0

---

.github/workflows/ci.yml
src/hdf5plugin/test.py

This PR adds a basic test to make sure compression is actually doing something (when it should)
This follows issue #121, and is a basic way to avoid this in the future.
closes #124

Added tests checking filters compression

---

src/hdf5plugin/__init__.py

This PR removes python2 compatibility code that was remaining and is now useless.

Removed python2 compatibility code

---

.readthedocs.yml

This PR adds readthedocs config file for the project.

Added read the docs config

---

src/hdf5plugin/__init__.py

Changed level of "filter already loaded, skip it." log to info

---

setup.py

This PR adds an effective check of native compilation flags availability because it is not available for universal2 build on macos.
Related to #186

Build: Added check of native flags availability

---

appveyor.yml

Besides testing Python 3.10, it also updates to Visual Studio 2019

[CI] Test Python 3.10 under windows

---

.readthedocs.yml

This PR update the readthedocs configuration to remove deprecated features and tries spare building the filters which are not needed to generate the documentation.

Updated readthedocs configuration

---

README.rst
doc/conf.py
doc/index.rst
doc/usage.rst

This PR updates lists of filters in the documentation and the copyright year.

Fixed documentation

---

CHANGELOG.rst
src/hdf5plugin/_version.py

Prepare 4.0.1

---

setup.py
src/hdf5plugin/_filters.py

This would allow a preliminary release.

SZ3 Pre-release

---

doc/contribute.rst
doc/index.rst
doc/usage.rst
src/hdf5plugin/_filters.py

Can more mode be added to the doc?
closes #225

Added SZ3 to documentation

---

setup.py

Added HDF5PLUGIN_BMI2 to config available at runtime

---

CHANGELOG.rst
src/hdf5plugin/_version.py

Updated changelog, bump to v4.1.0

---

setup.py
src/hdf5plugin/test.py

This PR changes SZ compression filter build options to fix an issue with SZ absolute mode.
I added the test from issue #267
closes #267

Fixed SZ compression filter build options

---

appveyor.yml

Replace Python 3.11 by Python 3.12

[CI] Appveyor test Python 3.12

---

CHANGELOG.rst
src/hdf5plugin/_version.py

Update changelog and bump to version 4.3.0

Prepare a 4.3.0 release

---

doc/conf.py

it's already 6 months into the new year. Time to update the documentation. ;-)

updated copyright statement

---

CHANGELOG.rst
src/hdf5plugin/_version.py

~~Merge #336 and #337 first!
And set the date in `CHANGELOG.rst`.~~
Update changelog and bump version to 5.1.0.

Prepare v5.1.0

---

.github/workflows/release.yml
CHANGELOG.rst
doc/contribute.rst

~~Merge PR #360 first!~~
This PR updates the changelog and fixes a typo in the doc.
The version number is already `"6.0.0"`

Prepare v6.0.0
