- CHANGELOG.rst
- hdf5plugin/__init__.py
- setup.py
> New PyPI release 1.2.0

- README.rst
This PR fixes a small typo following filter IDs renaming
> Fix typo in sample code

- setup.py
This PR updates the bdist_wheel command override by not setting `root_is_pure = True`.
This way, the generated wheel is cleaner.
closes #48
> Improve bdist_wheel override

- README.rst
- setup.py
This PR adds an option to build the bitshuffle plugin with (or without) OpenMP.
It is enabled by default except on macOS.
To use the option, run: `python setup.py build --openmp=[False|True]`
closes  #24
> Bitshuffle add option to build with OpenMP

- README.rst
This PR adds instruction for installing with conda in the readme as hdf5plugin has just been added in conda-forge.
Many thanks @tschoonj for the packaging!
related to #17
> Add conda installation instruction

- MANIFEST.in
- README.rst
- cpuinfo.py
- setup.py
This PR adds `--sse2` and `--avx2` build options to enable/disable SIMD instructions for blosc and bitshuffle.
closes #23
TODOS:
> Add options to use SSE2 and AVX2 (for bitshuffle and blosc)

- CHANGELOG.rst
- README.rst
- hdf5plugin/__init__.py
- hdf5plugin/test.py
- setup.py
This PR adds snappy to blosc if C++11 is available.
Usage of C++11 can be disabled with the `--cpp11=False` build option.
closes #41
closes #55
> Add snappy to blosc if c++11 is available

- setup.py
This PR refactors the build to make it work on macOS with C++11.
It builds snappy (C++11) as a static library only if C++11 is used.
This needs a bit a tweaking as checking for compile flags can only be done late in the process with setuptools...
closes #58
> Rework build to build snappy as a static lib first

- ci/travis_osx.sh
Install miniconda on macos to use python3: closes #65
> [CI] Use python3 on macos

- README.rst
- Correct typo on filter name.
- Mention the availability of FCIDECOMP and ZFP in the first sentence.
> Correct typo

- README.rst
- doc/compression_opts.rst
- hdf5plugin/__init__.py
- hdf5plugin/test.py
This PR adds optional parameters to the `Zfp` filter in order to configure the compression mode.
It documents those modes in the README and add tests for it.
> Add Zfp parameters

- .travis.yml
This PR adds `twine check` to travis CI so as to detect possible issues with packaging for pypi.
> Add twine check test

- setup.py
This PR fixes the build with latest version of the `wheel` package.
I also tested the fix with previous versions of `wheel`
> Fixed support of wheel version>=0.35

- CHANGELOG.rst
- version.py
This PR synchronizes the `version.py` file with that of silx and prepare for a 2.3.1 bug fix release.
> Prepare v2.3.1

- setup.py
This PR supersedes  PR #89.
It is based on PR #89, but avoids to modify `src/bitshuffle` by setting macros from `setup.py`.
It also enables SSE2 support for ppc64le in a generic way.
Finally it prevents blosc to use SSE2 shuffle implementation on power9 since this implementation relies on x86 assembly code.
> enable SIMD on power9 for bitshuffle filter

- CHANGELOG.rst
- version.py
This PR prepares a beta version in order to have a tag to make a ubuntu package for power9 with bitshuffle filter optimization.
> Prepare 2.3.2b0

- CHANGELOG.rst
- test/test.py
Minor PR to avoid `numpy` v1.20rc1 deprecation warning in tests.
> Avoid numpy 1.20 deprecation warning

- README.rst
- hdf5plugin/__init__.py
- hdf5plugin/test.py
- setup.py
- src/HDF5Plugin-Zstandard/.gitignore
- src/HDF5Plugin-Zstandard/CMakeLists.txt
- src/HDF5Plugin-Zstandard/LICENSE
- src/HDF5Plugin-Zstandard/README.md
- src/HDF5Plugin-Zstandard/zstd_h5plugin.c
- src/HDF5Plugin-Zstandard/zstd_h5plugin.h
Main issue is we do not have any test data.
closes  #93
> Add Zstd to the supported plugin list

- setup.py
closes #108
It still need to be tested for `manylinux1`.
> Add -std-c99 to blosc compile flags to build for manylinux1

- hdf5plugin/__init__.py
- hdf5plugin/test.py
- setup.py
This PR adds a `hdf5plugin.config` namedtuple that allows to retrieve the build options (e.g., openmp, cpp11).
This is achieved by writing a python file with a dict definition containing this information from `setup.py`.
In case the build options change between 2 builds, a `clean` is done first to rebuild everything.
The way to deal with this sounds simple enough to me, but if there is a better way to do so, I'll take it.
This PR also avoid error message of `fcidecomp` filter if not build with C++11 and adds an error message when using the `FciDecomp` class.
closes #96, related to #112, hopefully closing it
> Added `hdf5plugin.config` to retrieve build options at runtime; Fixed `FciDecomp` error message when built without c++11

- .github/workflows/ci.yml
- setup.py
This PR should add support for M1 by disabling SSE2 and AVX2 on `arm64` machines.
It also adds env var to configure default build options (useful with `cibuildwheel`)
~This is UNTESTED!~
> Added ARM64 support; Added build config with environment variables

- CHANGELOG.rst
- MANIFEST.in
- build-deb.sh
- setup.py
Fix `sdist_debian` broken following move of `version.py` (PR #114):
Updated `get_version()`,  `sdist_debian.get_debian_name` and `build-deb.sh` from silx (+ using `python -B`).
Also added `author_email` to remove a warning: "author_email needed when author is set"
> Fixed debian/ubuntu packaging

- setup.py
This PR fixes installation from source through `python setup.py install`.
Indeed in this case the build command is not run... so I moved the `_config.py` file creation to `build_py` which should be run in any case.
It also fixes a deprecatio. warning and add zip_safe=False to avoid the check.
Related to #122
> Fixed installation through setup.py install

- setup.py
For mips64el CPU, disable SSE2 and AVX2 in line 79,
and use -march=native in line 323.
> Update setup.py to support mips64el

- setup.py
Users who do not pin their version to a specific version installing from Python 2 will get an error when trying to install the library, rather than being directed to install an earlier version automatically by the package index.
> Express Python version as an install requirement

- src/hdf5plugin/test.py
This avoids tests to fail when `hdf5plugin`is built without C++11 support and `snappy` is not available.
> Improved tests: Skips blosc with snappy tests when C++11 is disabled

- doc/information.rst
Fixed typo and change `master` to `main` in links.
> Fixed typo in license link

- cpuinfo.py
- setup.py
- src/hdf5plugin/__init__.py
This PR reworks the way build options (namely, `cpp11`, `sse2`, `avx2`, `native` and `openmp`)  are managed.
The current behaviour (since v3.0.0, PR #116) is:
- default values are `True` (except for `openmp` set to `False` on mac OS).
- `HDF5PLUGIN_*` environment variables overrides the defaults if they are set.
- Command line provided build options (e.g., `python setup.py build --sse2=False`) overrides defaults and env. vars
- After all that, options are checked against the current platform/compiler and disabled if not available.
This was making its best to avoid build failure by checking options at the end.
At the same time, this caused issues in supporting `arm64` and `mips64`, each time needing specific handling (see PR #116 and #126 ).
The proposed behaviour is:
- default values are …
> Changed build options override priority order

- cpuinfo.py
- setup.py
- src/hdf5plugin/__init__.py
Merge PR #130 first! Then it boils down to commit e9da8aa
This PR adds usage of compilation options from build configuration when building C libraries used by compression filters (namely, snappy, charls, zfp).
Without this, configured compilation options are used to build the compression filter but not the libraries they rely on.
> Build clib options

- doc/install.rst
Copy-paste error in env. var. names
> Fixed documentation typo

- src/hdf5plugin/__init__.py
- src/hdf5plugin/test.py
> Add clevel argument for Zstd

- .github/workflows/ci.yml
- doc/install.rst
- pyproject.toml
- requirements.txt
- setup.py
This PR adds the missing `pyproject.toml` file to the project.
It also deprecates build options passed through the command line since calling `setup.py` directly is now deprecated.
closes #131
> Added pyproject.toml

- setup.py
- src/hdf5plugin/__init__.py
- src/hdf5plugin/test.py
- test/test.py
This PR adds a build time option to remove some/all hdf5 compression filters from the build of hdf5plugin.
This provides a way for packagers to bundle the compression filters separately, yet providing hdf5plugin API.
This is controlled through the undocumented `HDF5PLUGIN_STRIP` env. var.
It also provides the list of embedded filters through `hdf5plugin.config.embedded_filters`. It is generated from HDF5PLUGIN_STRIP and also when building without C++11 where fcidecomp cannot be compiled.
closes #162
> Added `config.embedded_filters` to advertise embedded filters, and HDF5PLUGIN_STRIP to configure it

- setup.py
This PR removes passing `define_macros` to Zstd filter since the pass argument is the `define_macros` from blosc.
> Clean-up `setup.py`

- doc/usage.rst
- src/hdf5plugin/__init__.py
This makes it inline with `HDF5_PLUGIN_PATH` env. var. name.
closes #175
> Renamed `PLUGINS_PATH` constant to `PLUGIN_PATH` without `S`

- src/hdf5/include/H5public.h
- src/hdf5_dl.c
PR #172 fixed the use of `H5[free|allocate]_memory` by patching the hdf5 headers... which obviously does not work with user provided headers.
This PR provides `H5[free|allocate]_memory` functions which calls directly `free`/`allocate`.
closes #177
> Fixed LZ4 filter compilation with HDF5PLUGIN_HDF5_DIR

- doc/usage.rst
- src/hdf5plugin/__init__.py
This PR:
- adds a debug log when successfully registering a filter.
- adds and document a `get_config()` function with provides access to both build-time options and runtime registered filters.
Previously `hdf5plugin.config` was available (and still is) to provide build time config but it is not documented.
I hesitated between providing a dedicated `get_registered_filters()` function and providing a more general `get_config()` one as this PR proposes. I chose the later to avoid having too many functions for accessing debug/more advanced information. Any other opinion? Better naming?
closes #185
> Added `get_config()` function to retrieve information

- setup.py
This PR is a follow-up of PR #169 for stripping compression filters from the package at build time.
It adds:
- filtering out of C libraries from the build when they correspond to stripped filters.
- support for a `"all"` value which strips all filters at once.
Filtering out stripped plugins is moved from inside the `build` command to before calling `setup()` since there is no need to be inside the command to do it.
> Build: Updated `HDF5PLUGIN_STRIP` behaviour and added support for `"all"` value

- setup.py
This PR adds `-O3` and `-ffast-math` to blosc filter compilation.
From what I tested it seems to improve blosc+bitshuffle+lz4 performance... but not sure of other side effects...
> Added optimisation flags for blosc filter compilation

- src/hdf5plugin/__init__.py
This PR:
- Provides a small update for the logging by providing the traceback in case of catched exception
- Removes unsued `registered_filters` variable
- Replaces `"unknown"` string by `None` for the ctypes lib object
> Updated logging, code clean-up

- README.rst
- doc/index.rst
- doc/information.rst
- package/debian10/control
- package/debian11/control
This PR fixes the list of filters in the documentation: bzip2 and zstd were not advertised.
It also advertises the recently created Zenodo DOI: https://doi.org/10.5281/zenodo.7257761
> Updated documentation; Added Zenodo DOI

- src/hdf5plugin/_filters.py
- src/hdf5plugin/test.py
My changes:
- Docstring with a basic description and a link to the reference webpage.
- Renamed arguments to be self-explanatory (absolute, relative, pointwise_relative)
- Added a default value as pointwise_relative=1.e-05 to match numpy's allclose.
> Add SZ: Docstrings, self-explanatory arguments and default value.

- doc/usage.rst
- src/hdf5plugin/__init__.py
- src/hdf5plugin/_utils.py
- src/hdf5plugin/test.py
This PR adds a `register(filters=FILTERS, force=True)` function to the API.
With this function it is possible to manually re-register filters embedded in `hdf5plugin`.
The main use case should be to make sure embedded filters are use, which is done with:
```python
import hdf5plugin
hdf5plugin.register()
```
Related to #204
> Added `register` function

- doc/contribute.rst
- doc/usage.rst
- src/hdf5plugin/__init__.py
- src/hdf5plugin/_filters.py
- src/hdf5plugin/_utils.py
- src/hdf5plugin/test.py
This PR adds a `get_filters` function to retrieve filter classes from names or IDs.
By default is returns all filter classes.
It accepts a special argument "registered" and then returns classes of all currently registered filters.
The `register` function was also extended to supports IDs.
The `FILTERS` constant was removed from the documentation (not deprecated though): one can get filter classes with `get_filters` and then retrieve the `filter_id` from the filter classes.
A `filter_name` class attribute was also added to filter classes so one can get it from a class and it is shown in the documentation along with the classes.
Question: Is it really worth adding this `filter_name` which is specific to `hdf5plugin` to the API or not?
@rayosborn would that fits your need?
This PR also fixes …
> Added `get_filters` function; Fixed `register`

- doc/contribute.rst
- doc/usage.rst
- src/hdf5plugin/_filters.py
- src/hdf5plugin/test.py
This PR follows #206 to add and update a few things.
> Updated SZ support

- .flake8
- setup.py
- src/hdf5plugin/__init__.py
- src/hdf5plugin/_filters.py
- src/hdf5plugin/_utils.py
- src/hdf5plugin/_version.py
- src/hdf5plugin/test.py
~~Merge PR  #215 first!~~
This PR: 
- [Fixes code style with flake8](https://github.com/silx-kit/hdf5plugin/commit/72a372410d5a68b87d4059e45bdac5120209a50b)
- [Adds flake8 config](https://github.com/silx-kit/hdf5plugin/commit/042d29107a9ac3ae5642c0a3aad5d4fa0da6c0e7)
- [Deprecates date, hexversion, strictversion](https://github.com/silx-kit/hdf5plugin/commit/b90d230f6be6476986d1e2780d39de61f489873e)
- ~~Proposes to [stop using FILTER_ID](https://github.com/silx-kit/hdf5plugin/commit/be278422d7ab7d8cb6020e97c1910bee3d94cdab) in favor of `Filter.filter_id`: So remove `FILTER_ID` introduced since last version.~~
> Fixed code style; Deprecated `date`, `hexversion` and `strictversion`

- src/hdf5_dl.c
@t20100 
Our default for H5Tget_order does not seem to be correct. It should be negative in case of error.
> Needed when compiling as C++ inside extern "C" {}

- src/hdf5_dl.c
H5T_ORDER_ERROR is not 0 but negative.
Using HDF5 library constants also solves issues when compiling the code with C++ compilers.
> Provide correct HDF5 defaults

- setup.py
- src/hdf5plugin/_filters.py
- src/hdf5plugin/_utils.py
- src/hdf5plugin/test.py
This PR aims at:
- making `setup.py` hopefully a bit easier to read by splitting the build config of static libs and plugins by using functions rather.
- building static library of compressors shared by multiple filters as well as the `hdf5_dl.c` file to avoid building multiple times the same code.
It also fixes some `flake8` linting issues, in particular a typo in `_utils.py` using `_logger` instead of `logger`.
closes #220
> Updated build setup to share some build steps

- doc/install.rst
- setup.py
- src/hdf5plugin/test.py
~~Merge PR #240 first!~~
This PR adds a check for C++14 availability as there was one for C++11 (https://github.com/silx-kit/hdf5plugin/commit/3afa9a448d0115247c3bedd1a38c3e454cddd5c9).
This follows the addition of the SZ3 filter.
It also cleans-up testing python version >=3.5 for available of MSVC compilation options since >=3.7 is required (https://github.com/silx-kit/hdf5plugin/commit/711ee768786361f8d81acdaa339bba6b9c427218).
> Added check availability of C++14

- ci/info_platform.py
- setup.py
This PR removes direct import of `distutils` where possible.
What remains is:
```python
import distutils.ccompiler
import distutils.errors
import distutils.sysconfig
```
Related to #193
> Reduce usage of `distutils`

- doc/information.rst
- doc/install.rst
- setup.py
- src/bitshuffle/.github/dependabot.yml
- src/bitshuffle/.github/workflows/lint.yml
- src/bitshuffle/.github/workflows/main.yml
- src/bitshuffle/.github/workflows/wheels.yml
- src/bitshuffle/README.rst
- src/bitshuffle/bitshuffle/__init__.py
- src/bitshuffle/bitshuffle/ext.pyx
- src/bitshuffle/setup.cfg.example
- src/bitshuffle/setup.py
- src/bitshuffle/src/bitshuffle_core.c
- src/bitshuffle/src/bitshuffle_core.h
- src/bitshuffle/src/bshuf_h5filter.c
- src/bitshuffle/src/bshuf_h5filter.h
- src/bitshuffle/src/iochain.c
- src/bitshuffle/src/iochain.h
- src/bitshuffle/tests/make_regression_tdata.py
- src/bitshuffle/tests/test_ext.py
This PR:
- Adds support for enable AVX512 "Foundation" and "Byte and Word" instruction sets. This can be configured through the `HDF5PLUGIN_AVX512` env. var. Else it is probed with `cpuinfo` and checking compile flag availability.
- Updates the version of `bitshuffle` embedded to v0.5.1. This version uses AVX512 F and BW.
- Updates the links of lz4 and zstd as a follow-up of #250 
closes #236
> Updated `bitshuffle` to v0.5.1; Added `HDF5PLUGIN_AVX512` configuration environment variable

- doc/information.rst
- src/c-blosc2/blosc/CMakeLists.txt
- src/c-blosc2/blosc/shuffle.c
This PR applies a patch to `c-blosc2` to fix an issue with selecting the right implementation depending on available SIMD.
See https://github.com/Blosc/c-blosc2/pull/436
> Fixed `blosc2`: Added patch from c-blosc2 PR #436

- setup.py
This PR enables Neon support for `blosc2` with ARM.
On macOS (at least) no compilation flag needs to be passed for enabling Neon.
This PR also simplifies the build of `blosc` and `blosc2` since now architecture specific source files compiles even on wrong architecture, thanks to e.g., `#if defined(__ARM_NEON) .. #endif` (this was need for supporting `universal2` build).
Full test matrix of this PR is available here: https://gitlab.esrf.fr/silx/bob/hdf5plugin/-/pipelines/100336
closes #244
> Enabled ARM Neon support for `blosc2`; Updated `blosc` and `blosc2` build configuration

- doc/information.rst
This PR reworks the list of filter and compression libs source links.
The goal is to make it simpler to maintain by avoiding duplicated links to compression libs using by mulitple filters.
It also simplifies the display by not displaying the URLs any more.
See previous: http://www.silx.org/doc/hdf5plugin/4.0.0/information.html#hdf5-filters-and-compression-libraries
> Updated documentation

- .github/workflows/ci.yml
- appveyor.yml
- Upgrade latest h5py to 3.8.0
- Upgrade windows tests to python 3.11
> [CI] Test h5py 3.8.0

- CHANGELOG.rst
- setup.py
- src/hdf5plugin/_version.py
This PR fixes build on ARM with gcc by adding necessary flags (as in c-blosc2 cmakefile).
Tested on macos/ARM, raspberrypi and with conda-forge environement for cross-compilation of `aarch64`.
It also prepare for a 4.1.1 bug fix release.
closes #260
> Fixed blosc2 compile flags on ARM hosts; Prepare v4.1.1 release

- src/hdf5plugin/_utils.py
This PR replaces the use of `ctypes` to access `H5Zregister` with the corresponding wrapper available in `h5py` (see https://github.com/h5py/h5py/pull/2229): `h5z.register_filter` when it is available.
> Use `h5py.h5z.register_filter` if available

- .github/workflows/ci.yml
This PR fixes the CI and update github actions/checkout and actions/python to the latest versions.
closes #274
> Updated CI configuration

- pyproject.toml
- requirements.txt
- setup.py
This PR requires at least wheel>=[0.34.0](https://pypi.org/project/wheel/0.34.0/) (from January 2020).
This simplifies a bit `setup.py` and remove deprecated dependency on `pkg_resources`
> Updated dependency to `wheel`>=0.34.0

- package/debian11/control
- setup.py
This PR aims at removing the import of `distutils` by using an approach proposed in https://github.com/pypa/setuptools/issues/2806#issuecomment-961805789.
Imports of `distutils` as fallbacks for older versions of `setuptools` are kept for now.
related to  #193
> Removed import of `distutils`

- doc/information.rst
- src/PyTables/hdf5-blosc2/src/blosc2_filter.c
- src/PyTables/hdf5-blosc2/src/blosc2_filter.h
- src/hdf5plugin/_filters.py
- src/hdf5plugin/test.py
This provides a few updates to support Blosc2 NDim NDim (2-level partitioning or b2nd, as introduced in Blosc2 2.7.0, see <https://www.blosc.org/posts/blosc2-ndim-intro/>) for arrays with rank >= 2. The code comes from PyTables master commit bb02c88 (where it passes all tests); part of it was already released in PyTables v3.9.0 and the rest will be in the next version (though it is completely compatible with the released one and not expected to change until then). A minor documentation fix and an updated unit test are also included.
For such b2nd-enabled arrays, each HDF5 chunk is stored as a Blosc2 multidimensional array with a fixed shape (even for margin chunks where data may not cover the whole chunk), consisting of a single inner chunk itself, and it also adds the HDF5 chunk rank and …
> Update hdf5-blosc2 to support b2nd

- doc/conf.py
This PR updates the sphinx documentation to accomodate change of default theme in readthedocs: https://github.com/readthedocs/readthedocs.org/pull/10638
> Updated documentation configuration to accomodate changes in readthedocs

- README.rst
- doc/contribute.rst
- doc/index.rst
- package/debian11/control
- package/debian12/control
This PR updates the link to the registered filters on the hdf5 website that was broken
> Documentation: Updated link to hdf5 registered filters

- src/hdf5plugin/test.py
- test/test.py
This PR updates SZ3 tests to relax the test to check that previously compressed data still respects the given constraints rather providing an exact match.
> SZ3 filter: Updated tests

- .github/workflows/release.yml
- src/hdf5plugin/test.py
- test/test.py
⚠️ Need to sort out PR #290 first (included here so that all tests pass)
The contribution of this PR is commit fef816569c05c43a715bbbd9660091cc5a42bae7
This PR proposes to add github actions workflow to build the wheels and tarball and deploy them to pypi.
The workflow builds wheels for windows (x86_64), macos (x86_64 and arm64) and linux (x86_64, ppc64le and aarch64) using cibuildwheel.
This workflow can be run manually and is run automatically when creating a "release" through github.
When the workflow is started from a "release", the created tarball and wheels are uploaded to pypi, if: build and tests are successful **and** the deployment is manually approved (This still needs some setup on both pypi and github side, but it's no big deal).
Here is a run of this workflow: …
> Added a release github action workflow

- doc/information.rst
- src/c-blosc2/ANNOUNCE.md
- src/c-blosc2/RELEASE_NOTES.md
- src/c-blosc2/blosc/blosc-private.h
- src/c-blosc2/blosc/blosc2.c
- src/c-blosc2/include/b2nd.h
- src/c-blosc2/include/blosc2.h
This PR updates `c-blosc2` to the latest release [v2.13.1](https://github.com/Blosc/c-blosc2/releases/tag/v2.13.1)
> Updated c-blosc2 v2.13.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
This PR updates actions used by CI workflows:
- cibuildwheel: To fix an issue on Windows (see https://github.com/pypa/cibuildwheel/releases/tag/v2.16.5)
- upload|download-artifact: To enable downloading the produced artifacts from the github action page.
- setup-python and checkout: To avoid warnings
> Updated continuous integration configuration

- src/hdf5plugin/_filters.py
Just ran into this problem and would like to avoid other users to see a ValueError if they do:
```python
f = h5py.File('test.h5', 'w')
f.create_dataset(
'bitshuffle_with_lz4',
data=numpy.arange(100),
**hdf5plugin.Bitshuffle(nelems=0, lz4=False, cname='zstd'))
f.close()
```
> avoid throwing ValueError if user sets lz4=False

- src/hdf5plugin/_filters.py
Remove duplicated information in `Bitshuffle` docstring.
> Documentation: Fixed typo in `Bitshuffle` docstring

- .readthedocs.yml
- README.rst
- doc/index.rst
This PR fixes the broken link to HDF5 registered filters and add Sperr to the list of filters
> Documentation: Fixed broken link, Fixed readthedocs configuration

- setup.py
This PR removes `/openmp` link flags on Windows to avoid the following warning:
` LINK : warning LNK4044: unrecognized option '/openmp'; ignored`
> Build: Fixed compilation warning on Windows by removing `/openmp` link flags

- .github/workflows/release.yml
- doc/contribute.rst
- doc/index.rst
- doc/information.rst
- doc/usage.rst
- src/hdf5plugin/_filters.py
- src/hdf5plugin/_version.py
This PR updates the documentation to fix some broken links.
It also adds the documentation build to the release workflow.
> Documentation: Updated and fixed broken links; CI: Added documentation build to release workflow

- setup.py
For c-blosc2 on P9, this PR only enables the altivec code and disables all the others.
Otherwise, there is a compilation error:
```
src/c-blosc2/blosc/shuffle.c: In function ‘blosc_get_cpu_features’:
src/c-blosc2/blosc/shuffle.c:272:29: error: ‘HWCAP_ARM_NEON’ undeclared (first use in this function)
272 |   if (getauxval(AT_HWCAP) & HWCAP_ARM_NEON) {
|                             ^~~~~~~~~~~~~~
src/c-blosc2/blosc/shuffle.c:272:29: note: each undeclared identifier is reported only once for each function it appears in
error: command '/usr/bin/powerpc64le-linux-gnu-gcc' failed with exit code 1
```
The error was due to trying to compile arm code on P9. This code is now explicitly disabled by changing the defined C macros.
> Fixed `c-blosc2` compilation issue on `ppc64le`

- .github/workflows/release.yml
- CHANGELOG.rst
- src/hdf5plugin/_version.py
This PR prepares for the release of v5.0.
It bumps the release number and updates the changelog.
It also use `numpy<2` for tests during the release workflow since wheels of h5py v3.11 which supports numpy v2 are not available for `aarch64` and `ppc64le`.
> Prepare v5.0.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
- setup.py
This is intended for debian packaging, closes #328
`setup.py` should no longer fail even if the embedded filters are removed from the source.
Also update CI config to use `macos-13` and updated cibuildwheel action, closes #325
> Build: Fixed strip all embedded filters issue with missing plugin folders; CI: Use macos-13

- doc/information.rst
- setup.py
- src/H5Z-SPERR/.gitignore
- src/H5Z-SPERR/CMakeLists.txt
- src/H5Z-SPERR/README.md
- src/H5Z-SPERR/include/compactor.h
- src/H5Z-SPERR/include/h5zsperr_helper.h
- src/H5Z-SPERR/include/icecream.h
- src/H5Z-SPERR/src/CMakeLists.txt
- src/H5Z-SPERR/src/compactor.c
- src/H5Z-SPERR/src/h5z-clamp.c
- src/H5Z-SPERR/src/h5z-sperr.c
- src/H5Z-SPERR/src/h5zsperr_helper.cpp
- src/H5Z-SPERR/src/icecream.c
- src/H5Z-SPERR/test_scripts/CMakeLists.txt
- src/H5Z-SPERR/test_scripts/compactor_test.cpp
- src/H5Z-SPERR/test_scripts/h5zsperr_helper_test.cpp
- src/H5Z-SPERR/test_scripts/icecream_test.cpp
- src/hdf5plugin/_filters.py
- src/hdf5plugin/test.py
This MR updates h5z-sperr to version ~~[0.2.1](https://github.com/NCAR/H5Z-SPERR/releases/tag/v0.2.1)~~ [0.2.3](https://github.com/NCAR/H5Z-SPERR/releases/tag/v0.2.3).
A new `cd_values` is added to pass ["missing_value_mode"](https://github.com/NCAR/H5Z-SPERR/tree/v0.2.1?tab=readme-ov-file#handling-of-missing-values)
> Updated compression filer `h5z-sperr` v0.2.3

- setup.py
This PR adds conversion of `-L` `-l` to MSVC `/LIBPATH:` and `*.lib` suffix.
This allows to build conda packages on Windows with system libraries (see https://github.com/conda-forge/hdf5plugin-feedstock/pull/59)
> Fixed build on Windows with system libraries

- .github/workflows/ci.yml
- .github/workflows/release.yml
- doc/contribute.rst
- pyproject.toml
- setup.py
- src/hdf5plugin/__init__.py
- src/hdf5plugin/_filters.py
- src/hdf5plugin/_utils.py
- src/hdf5plugin/test.py
- test/test.py
This PR:
- fixes warnings raised by [bandit](https://github.com/PyCQA/bandit) security linter = replacing `assert` with exceptions outside of test code.
- updates the syntax with [`pyupgrade --py38-plus`](https://github.com/asottile/pyupgrade)
- adds bandit to the CI
> Code quality: Fixed bandit warning, update code pyupgrade --py38-plus; CI: Added bandit check

- .github/workflows/ci.yml
- .github/workflows/release.yml
- ci/oldest_h5py.txt
- pyproject.toml
- src/hdf5plugin/_version.py
This PR updates the minimum required version of Python to 3.9.
This is needed for PR #344 which is needed so that it keeps working with `setuptools` released after February 2026...
The CI configs are updated to add python3.13 and remove 3.8.
This PR also updates those CI configs
> Updated minimum required version of Python

- setup.py
This PR removes the optimization flags making some float operations not compliant to IEEE-754.
Looking at the upstream embedded filters and libraries, `-ffast-math` and `/fp:fast` are only used by the `bitshuffle` project. I guess we copied them over to the other lib/filters.
Those flags are also not used in https://github.com/hdfgroup/hdf5_plugins
I propose to remove those possible risky compilation flags.
This will also solve some build issue on conda-forge (see https://github.com/conda-forge/hdf5plugin-feedstock/pull/64)
> Removed `-ffast-math` and `/fp:fast` compilation flags

- src/hdf5plugin/__init__.py
- src/hdf5plugin/_version.py
No need to maintain code for parsing a version string, `packaging.version.Version` does it if needed.
closes #354
> Deprecated `hdf5plugin.version_info`
